### PR TITLE
Upgrade neutrino packages

### PR DESCRIPTION
**Pull request by helfi92**

### CODE REVIEW

**Comment by helfi92** [comment]
Upgrading to latest neutrino throws errors.

_Running `yarn lint`_

```bash
➜  taskcluster-web-server git:(lint) ✗ yarn lint
yarn run v1.12.3
warning ../package.json: No license field
$ eslint --cache --format codeframe --ext mjs,js src test

An error occurred when loading the Neutrino configuration.

{ Error: Cannot find module 'babel-plugin-eslint-plugin-prettier' from '/Users/haali/Documents/Mozilla/projects/taskcluster-web-server'
- If you want to resolve "eslint-plugin-prettier", use "module:eslint-plugin-prettier"
    at Function.module.exports [as sync] (/Users/haali/Documents/Mozilla/projects/taskcluster-web-server/node_modules/resolve/lib/sync.js:43:15)
    at resolveStandardizedName (/Users/haali/Documents/Mozilla/projects/taskcluster-web-server/node_modules/@babel/core/lib/config/files/plugins.js:101:31)
    at resolvePlugin (/Users/haali/Documents/Mozilla/projects/taskcluster-web-server/node_modules/@babel/core/lib/config/files/plugins.js:54:10)
    at reduce (/Users/haali/Documents/Mozilla/projects/taskcluster-web-server/node_modules/babel-merge/dist/index.js:21:26)
    at Array.reduce (<anonymous>)
    at mergeArray (/Users/haali/Documents/Mozilla/projects/taskcluster-web-server/node_modules/babel-merge/dist/index.js:20:36)
    at babelMerge (/Users/haali/Documents/Mozilla/projects/taskcluster-web-server/node_modules/babel-merge/dist/index.js:40:19)
    at lintRule.use.tap.lintOptions (/Users/haali/Documents/Mozilla/projects/taskcluster-web-server/node_modules/@neutrinojs/mocha/src/index.js:11:11)
    at Object.tap (/Users/haali/Documents/Mozilla/projects/taskcluster-web-server/node_modules/webpack-chain/src/Use.js:14:20)
    at module.exports.neutrino (/Users/haali/Documents/Mozilla/projects/taskcluster-web-server/node_modules/@neutrinojs/mocha/src/index.js:7:28) code: 'MODULE_NOT_FOUND' }
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

_Running `yarn start`_

```bash
➜  taskcluster-web-server git:(lint) yarn start
yarn run v1.12.3
warning ../package.json: No license field
$ webpack --watch --mode development

An error occurred when loading the Neutrino configuration.

{ Error: Cannot find module 'babel-plugin-eslint-plugin-prettier' from '/Users/haali/Documents/Mozilla/projects/taskcluster-web-server'
- If you want to resolve "eslint-plugin-prettier", use "module:eslint-plugin-prettier"
    at Function.module.exports [as sync] (/Users/haali/Documents/Mozilla/projects/taskcluster-web-server/node_modules/resolve/lib/sync.js:43:15)
    at resolveStandardizedName (/Users/haali/Documents/Mozilla/projects/taskcluster-web-server/node_modules/@babel/core/lib/config/files/plugins.js:101:31)
    at resolvePlugin (/Users/haali/Documents/Mozilla/projects/taskcluster-web-server/node_modules/@babel/core/lib/config/files/plugins.js:54:10)
    at reduce (/Users/haali/Documents/Mozilla/projects/taskcluster-web-server/node_modules/babel-merge/dist/index.js:21:26)
    at Array.reduce (<anonymous>)
    at mergeArray (/Users/haali/Documents/Mozilla/projects/taskcluster-web-server/node_modules/babel-merge/dist/index.js:20:36)
    at babelMerge (/Users/haali/Documents/Mozilla/projects/taskcluster-web-server/node_modules/babel-merge/dist/index.js:40:19)
    at lintRule.use.tap.lintOptions (/Users/haali/Documents/Mozilla/projects/taskcluster-web-server/node_modules/@neutrinojs/mocha/src/index.js:11:11)
    at Object.tap (/Users/haali/Documents/Mozilla/projects/taskcluster-web-server/node_modules/webpack-chain/src/Use.js:14:20)
    at module.exports.neutrino (/Users/haali/Documents/Mozilla/projects/taskcluster-web-server/node_modules/@neutrinojs/mocha/src/index.js:7:28)
    at Neutrino.use (/Users/haali/Documents/Mozilla/projects/taskcluster-web-server/node_modules/neutrino/Neutrino.js:211:7)
    at Neutrino.use (/Users/haali/Documents/Mozilla/projects/taskcluster-web-server/node_modules/neutrino/Neutrino.js:216:12)
    at middleware.use.map.usage (/Users/haali/Documents/Mozilla/projects/taskcluster-web-server/node_modules/neutrino/Neutrino.js:236:44)
    at Array.map (<anonymous>)
    at Neutrino.use (/Users/haali/Documents/Mozilla/projects/taskcluster-web-server/node_modules/neutrino/Neutrino.js:236:26)
    at Neutrino.use (/Users/haali/Documents/Mozilla/projects/taskcluster-web-server/node_modules/neutrino/Neutrino.js:216:12)
    at middleware.use.map.usage (/Users/haali/Documents/Mozilla/projects/taskcluster-web-server/node_modules/neutrino/Neutrino.js:236:44)
    at Array.map (<anonymous>)
    at Neutrino.use (/Users/haali/Documents/Mozilla/projects/taskcluster-web-server/node_modules/neutrino/Neutrino.js:236:26)
    at module.exports (/Users/haali/Documents/Mozilla/projects/taskcluster-web-server/node_modules/neutrino/index.js:36:16)
    at Object.<anonymous> (/Users/haali/Documents/Mozilla/projects/taskcluster-web-server/webpack.config.js:3:18)
    at Module._compile (/Users/haali/Documents/Mozilla/projects/taskcluster-web-server/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (/Users/haali/Documents/Mozilla/projects/taskcluster-web-server/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at WEBPACK_OPTIONS (/Users/haali/Documents/Mozilla/projects/taskcluster-web-server/node_modules/webpack-cli/bin/convert-argv.js:133:13)
    at requireConfig (/Users/haali/Documents/Mozilla/projects/taskcluster-web-server/node_modules/webpack-cli/bin/convert-argv.js:135:6) code: 'MODULE_NOT_FOUND' }
error Command failed with exit code 1.
```

**Comment by helfi92** [comment]
@edmorley Any idea why this is happening?

**Comment by edmorley** [comment]
I believe this is because as of neutrinojs/neutrino#1182 `@neutrinojs/eslint` now uses an ESLint helper function to merge configurations rather than a home-grown merge, and this helper must validate the list of plugins, and is (correctly) reporting that the `plugins` entry is currently not in the expected format:
https://github.com/taskcluster/taskcluster-web-server/blob/be555aa922c99d787ec9136c5683ad2829fb825e/.neutrinorc.js#L5-L8

The plugin needs to be referred to as `prettier` (eslint adds the prefix), see:
https://github.com/prettier/eslint-config-prettier#installation

**Comment by edmorley** [comment]
If I remove `@neutrinojs/mocha` it works. The wrong merge function is being used in:
https://github.com/neutrinojs/neutrino/blob/0488010ea77a1a7a267f2d5cf3e5a4558789882d/packages/mocha/src/index.js#L11
(there should be too merge imports, one for babel-merge and one for deepmerge)

I'll open a Neutrino PR. (Guess just shows how few people use the Mocha preset that no one has hit it so far!)

**Pull request merged**
