### PR TITLE
Bug 1490723 - produce both "events" and "messages"

### PR DESCRIPTION
**Pull request by djmitche**
Events are the purpose-specific things with type information, while
messages are generic Pulse messages.  The pulse messages have a schema
but a very general one, with no specific form for the payload.

### CODE REVIEW

**Comment by djmitche** [comment]
Here's what the messages look like in the playground (with only some of the pulseMessages fields selected):

screenshot_2018-10-12 playground - http lamport r igoro us 3050 graphql 1
screenshot_2018-10-12 playground - http lamport r igoro us 3050 graphql

Do I have the pluralization right here?  It seems odd to have pulseMessages = { a single message }

**Comment by djmitche** [comment]
> Shouldn't `pulseMessages` return an array of messages instead of a single one?

It returns one message at a time, so no?  I admit GraphQL is still baffling to me :)

**Comment by eliperelman** [comment]
Ah, I see now. Yes, you will get the messages one at the time, but the methods are describing the subscription, not the return value since they are streamed. As such, the method should stay as is, since you are subscribing to pulse messages, not a single pulse message.

**Comment by eliperelman** [comment]
Just a random note: the `CC` property seems inconsistent with the rest of the REST API which uses camel/lower case property names.

**Comment by djmitche** [comment]
Makes sense re plurals.  As for the CC, yeah, maybe `cc` would be better.  It's not part of the REST API but part of AMQP.

**Comment by eliperelman** [comment]
@djmitche ok perfect, didn't notice that. So then it should be easy to translate in the pulse place for `cc` -> `CC`.

**Comment by djmitche** [comment]
@helfi92 are you using a different version of the playground?  I don't even see a "Query Variables" pane in mine.  And in typing out that "subscription Sample" I only see `Variable "$subscriptions" of required type "[PulseSubscription]!" was not provided.`

**Comment by helfi92** [comment]
I'm accessing the playground via `http://localhost:3050/playground`. How does yours look? I've had too many issues with the playground like not seeing the "Query Variables" pane. Maybe try a different browser just to test?

**Comment by djmitche** [comment]
Yeah, the playground seems pretty poor.  But,
```
subscription Sample {
  pulseMessages(subscriptions: [{exchange: "exchange/taskcluster-treeherder/v1/jobs", pattern: "#"}])
}
```
works OK (no query parameters).

I think the reason you're not seeing any messages is that your taskcluster-web-server does not have taskcluster credentials and/or a pulse namespace set up.  You'll want to add
```yaml
defaults:
  pulse:
    namespace: taskcluster-user-<yourname>
```
in user-config.yml, and then set `TASKCLUSTER_CLIENT_ID` etc. with `eval $(taskcluster signin)`.

The tc-web-server service does log about the lack of credentials, but it's in a debug message so it's easy to miss.  I'd be interested in other ways to do that.  I don't want to make the credentials mandatory, though, because they're not something we give out to everyone, and most development on the service does not require them.

**Comment by djmitche** [comment]
I suspect that's because of the async removals that @eliperelman recommended.. I'll put 'em back.

**Comment by djmitche** [comment]
Should be fixed now (I used `return Promise.resolve(..)`)

**Pull request merged**
